version: "3.9"

services:
  app:
    build: .
    container_name: ecommerce-api
    ports:
      - "8000:80"       # external:internal
    environment:
      ENV: "local"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "local"
      DB_PASSWORD: "local"
      DB_NAME: "ecommerce"
    volumes:
      - ./src:/app/src   # live reload during development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

